### ISSUE TITLE
Inspections can be very long

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app#53]
If I am logged in as pim@iconize.nl, I get 3170 inspections:
<img width="2160" alt="image" src="https://user-images.githubusercontent.com/7629987/136708702-f63b9bfb-b9f4-48de-baae-8a3bac55254e.png">

I think we should paginate /inspections and /alerts to about 100 per page. And add lazy loading if you scroll down further.

Building up the /diary screen takes about 5 seconds, after the data has been loaded.

**Comment by JuliaBD** [comment]
Fixed ages ago :)
