### ISSUE TITLE
Device settings box collapses when I enter a character in the key field

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app#54]
https://app-test.beep.nl/devices
at changing 1 character in the `key` field, the device box collapses.

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/7629987/139487219-e49efbe0-dc50-4b3c-abd7-c71a8811edf9.png">

and it looks like I cannot change the hardware id for a device that is not a BEEP device

**Comment by JuliaBD** [comment]
Fixed on test
