### ISSUE TITLE
Image upload feature?

### ISSUE THREAD

**Issue by octomike** [beepnl/beep-vue-app#65]
Hi there. First of all: I'm very new into :bee:-keeping and I am loving the beep.nl project and the app to track everything online. I'm also really looking forward to the first installation of the beep base!

I was just wondering if there are plans to implement some basic photo support in the app. For instance, I would love to attach a picture to my queens. Or is that something serious bee keepers don't really do? :sweat_smile:

**Comment by pvgennip** [comment]
Hi @octomike You can currently do that in an inspection, if you select the photo field in your personal checklist. Not yet in the queen/hive input. Beekeepers do usually only register the items available for their Queen.
