### ISSUE TITLE
Empty screen when first loading data.

### ISSUE THREAD

**Issue by wasalm** [beepnl/beep-vue-app#85]
When I open the beep app and open the tab 'Data', the data of my beehives are not instantly loaded. See image.

![Schermafbeelding 2023-02-24 om 18 53 47](https://user-images.githubusercontent.com/4749597/221267186-be40bfdf-485d-4772-a8bc-3a176660751e.png)

When I manually select a beehive it does load the data:

![Schermafbeelding 2023-02-24 om 18 54 54](https://user-images.githubusercontent.com/4749597/221267689-8b6f02d7-8997-4b40-b51f-17bba044aca5.png)

In the console I get the error messages:
    
    mT not found  temperature
    mT not found  humidity
    mT not found  precipIntensity
    mT not found  windSpeed
    mT not found  t_i
    mT not found  weight_kg
    mT not found  rssi
    mT not found  snr

It used to work before, but now it is broken.

For reference: I made my own beehive monitor system. To circumvent the LoRa data package limitation, I split my data into two different types. One containing the audio information and the other the weight and temperature etc. Hence, the contents of `https://api.beep.nl/api/sensors/measurements` looks something like

    {
      "id": 1312,
      "interval": "day",
      "relative_interval": true,
      "index": 0,
      "timeGroup": "day",
      "resolution": "10m",
      "measurements": [
        {
          "time": "2023-02-23T18:40:00Z",
          "t_i": 30.3,
          "weight_kg": 22.169964433593,
          "rssi": -118,
          "snr": -1.75,
          "s_bin098_146Hz": null,
          "s_bin146_195Hz": null,
          "s_bin195_244Hz": null,
          "s_bin244_293Hz": null,
          "s_bin293_342Hz": null,
          "s_bin342_391Hz": null,
          "s_bin391_439Hz": null,
          "s_bin439_488Hz": null,
          "s_bin488_537Hz": null,
          "s_bin537_586Hz": null,
          "temperature": null,
          "humidity": null,
          "precipIntensity": null,
          "windSpeed": null
        },
        {
          "time": "2023-02-23T18:50:00Z",
          "t_i": 30.6,
          "weight_kg": 22.171588537947,
          "rssi": -118.5,
          "snr": -2.5,
          "s_bin098_146Hz": 17.14,
          "s_bin146_195Hz": 21.52,
          "s_bin195_244Hz": 17.04,
          "s_bin244_293Hz": 19.12,
          "s_bin293_342Hz": 16.56,
          "s_bin342_391Hz": 18.17,
          "s_bin391_439Hz": 17.12,
          "s_bin439_488Hz": 19.28,
          "s_bin488_537Hz": 17.1,
          "s_bin537_586Hz": 19.27,
          "temperature": 5.79,
          "humidity": 93,
          "precipIntensity": null,
          "windSpeed": 5.14
        },
        {
          "time": "2023-02-23T19:00:00Z",
          "t_i": 30.5,
          "weight_kg": 22.170903342301,
          "rssi": -118,
          "snr": -1.875,
          "s_bin098_146Hz": 17.3,
          "s_bin146_195Hz": 21.48,
          "s_bin195_244Hz": 16.81,
          "s_bin244_293Hz": 19.24,
          "s_bin293_342Hz": 16.49,
          "s_bin342_391Hz": 18.23,
          "s_bin391_439Hz": 16.89,
          "s_bin439_488Hz": 18.97,
          "s_bin488_537Hz": 17.15,
          "s_bin537_586Hz": 19.37,
          "temperature": null,
          "humidity": null,
          "precipIntensity": null,
          "windSpeed": null
        },
        {
          "time": "2023-02-23T19:10:00Z",
          "t_i": 30.5,
          "weight_kg": 22.170218146655,
          "rssi": -118.5,
          "snr": -1.75,
          "s_bin098_146Hz": 17.39,
          "s_bin146_195Hz": 21.68,
          "s_bin195_244Hz": 16.89,
          "s_bin244_293Hz": 19.41,
          "s_bin293_342Hz": 16.64,
          "s_bin342_391Hz": 18.46,
          "s_bin391_439Hz": 17.21,
          "s_bin439_488Hz": 18.87,
          "s_bin488_537Hz": 17.25,
          "s_bin537_586Hz": 19.02,
          "temperature": 5.34,
          "humidity": 93,
          "precipIntensity": null,
          "windSpeed": 4.63
        },
        {
          "time": "2023-02-23T19:20:00Z",
          "t_i": 30.6,
          "weight_kg": 22.168847755363,
          "rssi": -118.5,
          "snr": -2.25,
          "s_bin098_146Hz": 17.48,
          "s_bin146_195Hz": 21.65,
          "s_bin195_244Hz": 17.03,
          "s_bin244_293Hz": 19.08,
          "s_bin293_342Hz": 16.79,
          "s_bin342_391Hz": 17.85,
          "s_bin391_439Hz": 17.27,
          "s_bin439_488Hz": 19.02,
          "s_bin488_537Hz": 17.3,
          "s_bin537_586Hz": 19.16,
          "temperature": 5.16,
          "humidity": 93,
          "precipIntensity": null,
          "windSpeed": 4.63
        },
        {
          "time": "2023-02-23T19:30:00Z",
          "t_i": 30.8,
          "weight_kg": 21.59938956407,
          "rssi": -118.5,
          "snr": -1.875,
          "s_bin098_146Hz": 17.36,
          "s_bin146_195Hz": 21.58,
          "s_bin195_244Hz": 17.1,
          "s_bin244_293Hz": 18.86,
          "s_bin293_342Hz": 16.75,
          "s_bin342_391Hz": 18.13,
          "s_bin391_439Hz": 17.22,
          "s_bin439_488Hz": 18.89,
          "s_bin488_537Hz": 17.15,
          "s_bin537_586Hz": 19.27,
          "temperature": null,
          "humidity": null,
          "precipIntensity": null,
          "windSpeed": null
        },

**Comment by JuliaBD** [comment]
Hi @wasalm, thank you for your message. This should be fixed in the newest version (3.1.2), hopefully live later this week.
